сделал задачу
urfu-2017/javascript-task-6 pull request #37
Opened 2017-11-15 16:59 UTC by meta1-heart

2017-11-15 16:59 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 24

2017-11-15 17:01 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 24

2017-11-15 17:02 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 24

2017-11-15 17:17 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 24

2017-11-15 18:04 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2017-11-18 14:12 UTC, Vittly requested changes
🍅 

есть замечания небольшие и вопросы,
а еще разрешают делать на классах, если тебе интересно

2017-11-18 14:12 UTC, Vittly commented on lib.js
> +
лишняя пустая стока (не удержался)

2017-11-18 14:12 UTC, Vittly commented on lib.js
> + * Сортировка друзей по именам
лучше в таком виде: "возвращает результат сравнения двух друзей по имени"

2017-11-18 14:12 UTC, Vittly commented on lib.js
> + * @param {Object} friendsToFind - Друзья, которых мы ищем
кажется, тут массив

2017-11-18 14:12 UTC, Vittly commented on lib.js
> + * Найти не приглашенных друзей
"Возвращает подмножество друзей, которых еще не пригласили"

2017-11-18 14:12 UTC, Vittly commented on lib.js
> + * @returns {Object} - Друзья, которых ещё не пригласили
массив?

2017-11-18 14:12 UTC, Vittly commented on lib.js
> + * @returns {Object} - Друзья, которых ещё не пригласили
если есть описание в стиле, который я предлагаю, то к `returns` можно ничего не писать

2017-11-18 14:12 UTC, Vittly commented on lib.js
> + * @param {Object} invitedFriends - Список приглашённых
это тоже судя по всему массив, а можно кстати хеш сделать - будет быстрее работать для большого числа друзей (так мысли вслух)

2017-11-18 14:12 UTC, Vittly commented on lib.js
> +            .reduce((accum, friend) => accum
`accum` -> `collectedFriends`

2017-11-18 14:12 UTC, Vittly commented on lib.js
> +                .concat(findUnvisitedFriends(friend.friends, accum)), [])
так красивее будет:

```js
currentLevelFriends = currentLevelFriends
    .reduce(
        (x, friend) => x.concat(
            findUnvisitedFriends(friend.friends, x)
        ),
        []
    )
    .map(...)
```

2017-11-18 14:12 UTC, Vittly commented on lib.js
> +                .concat(findUnvisitedFriends(friend.friends, accum)), [])
кстати еще можно так:

```js
currentLevelFriends = currentLevelFriends
    .map(friend => friend.friends)
    .reduce((x, friends) => x.concat(findUnvisitedFriends(friends, x))) // да, можно не писать второй аргумент!
    .map(...)
```

2017-11-18 14:12 UTC, Vittly commented on lib.js
> +            .map(name => friends.find(friend => friend.name === name));
хм тут получается путаница, давай аргумент назовем `allFriends`

2017-11-18 14:12 UTC, Vittly commented on lib.js
> +    return invitedFriends.filter(filter.statement);
мне немного не нравится, что если `maxLevel` будет равен нулю, то мы довольно много работы сделаем, пока не поймем, что всего-то надо вернуть пустой массив

2017-11-18 14:12 UTC, Vittly commented on lib.js
> +    this.friends = getFriends(friends, filter);
обычно все private-поля называют с подчерком, типа `_friends`

2017-11-18 14:12 UTC, Vittly commented on lib.js
> + * @returns {null|Object} - Вернет null, если обход закончен или Друга в противном случае
можно в описании написать: "Возвращает следующего друга или null, если обход закончен"

2017-11-18 14:12 UTC, Vittly commented on lib.js
> +    return this.done() ? null : this.friends.shift();
`shift` - дорогая операция, бы держал внутренний индекс

2017-11-18 14:12 UTC, Vittly commented on lib.js
> +    Iterator.call(this, friends, filter);
хм-хм итого `getFriends` вызовется дважды :( давай что-нибудь придумаем? хотя бы:

```js

function SomeIterator() {
    Iterator.apply(this, arguments);
}
```

2017-11-18 14:12 UTC, Vittly commented on lib.js
> +    Iterator.call(this, friends, filter);
более сложный вариант - вынести формирование коллекции в отдельный метод и звать его при первом `next` или `done`

2017-11-22 17:25 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2017-11-23 08:43 UTC, Vittly commented on lib.js
> +            .map(name => friends.find(allFriends => allFriends.name === name));
ты не тех переименовал в `allFriends` ))

2017-11-23 08:45 UTC, Vittly commented on lib.js
> +        currentLevelFriends = findUnvisitedFriends(currentLevelFriends, invitedFriends)
можно переписать так, чтобы один раз звать `findUnvisitedFriends`, а не два, ну да ладно

2017-11-23 08:47 UTC, Vittly commented on lib.js
> +    this._friends = getFriends(friends, filter, maxLevel);
и все-таки, тут получется, что `getFriends` зовется дважды. Один раз в конструкторе `Iterator`, другой раз - тут. Это можно поправить, если унести подготовку коллекции в отдельный метод `_prepare`:

```js
this._friends = this._prepare.apply(this, arguments);
```

а реализовать это метод по разному для `Iterator` и `LimitedIterator`

2017-11-23 08:48 UTC, Vittly commented
🍅 

осталась проблема с лишним вызовом `getFriends`, ее надо поправить

2017-11-23 08:49 UTC, meta1-heart commented on lib.js
> +    this._friends = getFriends(friends, filter, maxLevel);
Окей, понял

2017-11-23 11:48 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2017-11-26 06:12 UTC, Vittly approved these changes

2017-11-26 06:12 UTC, Vittly commented
отлично!

2017-11-26 06:12 UTC, closed without merging