Александр Чернышёв
urfu-2017/javascript-task-6 pull request #50
Opened 2017-11-16 08:25 UTC by aleksch

2017-11-16 08:25 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2017-11-16 08:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-16 08:59 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 24

2017-11-16 09:14 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2017-11-16 18:30 UTC, eugenest requested changes

2017-11-16 18:30 UTC, eugenest commented on lib.js
> +    let invetedFriends = friends
invited

2017-11-16 18:30 UTC, eugenest commented on lib.js
> +        .filter(f => f.best)
здесь и далее:
f не годится

2017-11-16 18:30 UTC, eugenest commented on lib.js
> +    let notInvited = f => !guestArray.includes(f);
я бы вынес эту функцию из getFriends

2017-11-17 06:56 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2017-11-17 09:31 UTC, eugenest approved these changes
let notInvited = friend => !guestArray.includes(friend);

если бы вынес, код стал бы проще

2017-11-17 09:31 UTC, closed without merging