Ишин Данил
urfu-2017/javascript-task-6 pull request #6
Opened 2017-11-11 12:29 UTC by Dan1elNeal

2017-11-11 12:31 UTC, honest-hrundel commented
:tomato: Превышено максимальное время выполнения тестов

2017-11-11 12:49 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 24

2017-11-11 13:31 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 24

2017-11-11 13:47 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 24

2017-11-11 13:53 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2017-11-11 14:00 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2017-11-15 09:28 UTC, dotokoto requested changes
В целом мне нравится, хорошо получилось! Поправь немного замечаний и напиши мне в слак, когда исправишь

2017-11-15 09:28 UTC, Dotokoto commented on lib.js
> +    constructor(friends, filter, level = Infinity) {
Как-то нечестно, что `Iterator` и `LimitedIterator` - это совсем одно и то же. Давай все-таки в `Iterator` не будет возможности передать `level`. Унеси эту логику в `LimitedIterator`

2017-11-15 09:28 UTC, Dotokoto commented on lib.js
> +        currentLevelFriends = nextLevelFriends;
Кажется, переменная `nexLevelFriends` лишняя

2017-11-15 09:28 UTC, Dotokoto commented on lib.js
> +    return invitedFriends.filter(filter._callback);
Почему метод назван через `_`,  что намекает на приватность, но ты его напрямую используешь?

2017-11-15 09:28 UTC, Dotokoto commented on lib.js
> +        nextFriends = nextFriends.filter(friend_ => !nextLevelFriends.includes(friend_));
Стоит давать более осмысленные имена, а не просто добавлять символ в конце. Подумай, чем отличаются переменные в циклах, и назови соответственно

2017-11-15 09:28 UTC, Dotokoto commented
:tomato:

2017-11-17 15:44 UTC, Dan1elNeal commented on lib.js
> +    constructor(friends, filter, level = Infinity) {
Пришлось слегка извернуться, чтобы два раза не вызывать `makeInvitedFriendsList`  при создании объекта класса `LimitedIterator` :)

2017-11-17 15:44 UTC, Dan1elNeal commented on lib.js
> +        currentLevelFriends = nextLevelFriends;
fixed

2017-11-17 15:45 UTC, Dan1elNeal commented on lib.js
> +        nextFriends = nextFriends.filter(friend_ => !nextLevelFriends.includes(friend_));
fixed

2017-11-17 15:49 UTC, Dan1elNeal commented on lib.js
> +    return invitedFriends.filter(filter._callback);
fixed. Но я думал так: раз это моя библиотека, то я то знаю, что делаю, и мне не грешно вызвать приватный метод)

2017-11-17 15:51 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2017-11-20 05:14 UTC, closed without merging